### ISSUE TITLE
bat的目录写死了，改成相对路径，windows python3得把第一行删掉运行

### ISSUE THREAD

**Issue by lucky-zwx** [grisse/mogudingRobot#2]

**Comment by lucky-zwx** [comment]
RequestsDependencyWarning: urllib3 (1.25.7) or chardet (2.2.1) doesn't match a supported version!

**Comment by grisse** [comment]
> 下载仓库中的mogudStart.bat文件(用来运行脚本)，**修改其中代码文件的路径**。 --- readme.md
